### ISSUE TITLE
Automatically crawl facebook and post data into wordpress

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MythicAngel/buetian.com-theme-wordpress#31]
```
New feature.
```

Original issue reported on code.google.com by `mas1...@gmail.com` on 17 Apr 2014 at 12:42

**Comment by MythicAngel** [comment]
It is not possible now because facebook does not give "all" data and it returns only 8~10 post per page in the returned resultset. This implies for 20k dataset, we need to make 2000 request and eventually run out of limit.

We can but won't give this feature anymore.
