### ISSUE TITLE
Facebook API not working

### ISSUE THREAD

**Issue by seoulgithub** [MythicAngel/buetian.com-theme-wordpress#44]
After transferring into a new host, now facebook API is not working because it cannot download OAUTH-TOKEN.

Somehow, this should be solved by using wp-environment.

**Comment by MythicAngel** [comment]
Due to continuous change in FB api, the only to cope is to use their official sdk (JS preferable). By using graph-explorer tool we can find which url to pass in the FB-Api call and creating a wordpress ajax function we can push the data into wordpress.
